interface Project {
  title: string;
  description: string;
  published: string;
  image: string;
  link: string;
  techs: string[];
}

const projects: Record<string, Project> = {
  opensail: {
    title: 'Opensail',
    description: 'Sophisticated Regatta Rating System',
    published: '18.12.2024',
    link: 'https://github.com/Megakuul/opensail',
    image: 'opensail.png',
    techs: ['svelte', 'go', 'gh:action'],
  },
  battleshiper: {
    title: 'Battleshiper',
    description: 'Serverless SvelteKit deployment platform backed by AWS',
    published: '04.10.2024',
    link: 'https://github.com/Megakuul/Battleshiper',
    image: 'battleshiper.svg',
    techs: [
      'go',
      'svelte',
      'aws:cloudformation',
      'aws:api-gateway',
      'aws:dynamodb',
      'aws:lambda',
      'aws:s3',
      'aws:eventbridge',
      'aws:batch',
      'aws:codedeploy',
    ],
  },
  'adb-proxy': {
    title: 'ADB Proxy',
    description: 'Minimalistic central-managed android adb proxy',
    published: '17.08.2024',
    link: 'https://github.com/Megakuul/adb-proxy',
    image: 'adb-proxy.png',
    techs: ['go', 'dart', 'flutter'],
  },
  leaderboard: {
    title: 'Leaderboard',
    description: 'Simple leaderboard system constructed on lowcost aws serverless infrastructure',
    published: '29.07.2024',
    link: 'https://github.com/Megakuul/leaderboard',
    image: 'leaderboard.svg',
    techs: [
      'go',
      'svelte',
      'aws:cloudformation',
      'aws:cloudfront',
      'aws:api-gateway',
      'aws:cognito',
      'aws:ses',
      'aws:dynamodb',
      'aws:lambda',
    ],
  },
  screensaver: {
    title: 'Screensaver',
    description: 'Windows screensaver application based on gdi32',
    published: '11.05.2024',
    link: 'https://github.com/Megakuul/screensaver',
    image: 'screensaver.png',
    techs: ['c', 'msbuild', 'gdi32'],
  },
  simplehttp: {
    title: 'SimpleHTTP',
    description: 'A minimalistic HTTP server library, complying with basic HTTP/1.1 standards',
    published: '28.04.2024',
    link: 'https://github.com/megakuul/simplehttp',
    image: '',
    techs: ['c++', 'bazel'],
  },
  jupa: {
    title: 'JuPa Website',
    description: 'Full rebuild of jupa-thun website with sveltekit and svelte-parallax',
    published: '19.04.2024',
    link: 'https://github.com/Megakuul/jupa',
    image: 'jupa.svg',
    techs: ['svelte', 'tailwind', 'daisyui', 'vercel'],
  },
  gbaas: {
    title: 'Gitbackup as a Service',
    description: 'Service construct to backup github-repositories to AWS S3 bucket at a low cost',
    published: '30.12.2023',
    link: 'https://github.com/Megakuul/Gitbackup-as-a-Service',
    image: 'gbaas.svg',
    techs: ['go', 'html', 'aws:cloudformation', 'aws:lambda', 'aws:s3'],
  },
  orbstrike: {
    title: 'Orbstrike',
    description: 'Simple game using a stateful auto-scaler infrastructure',
    published: '11.11.2023',
    link: 'https://github.com/Megakuul/orbstrike',
    image: 'orbstrike.png',
    techs: ['go', 'dart', 'flutter', 'grpc', 'redis', 'k8s'],
  },
  'backup-analyzer': {
    title: 'Backup Analyzer',
    description: 'Backup strategy and retention analysis tool',
    published: '26.09.2023',
    link: 'https://github.com/Megakuul/backup-analyzer',
    image: 'backup-analyzer.svg',
    techs: ['svelte', 'tailwind', 'daisyui', 'redis', 'vercel'],
  },
  'kerberos-sim': {
    title: 'Kerberos Simulator',
    description: 'Kerberos simulator on steroids',
    published: '13.09.2023',
    link: 'https://github.com/Megakuul/kerberos-sim',
    image: 'kerberos-sim.svg',
    techs: ['go', 'bazel', 'protobuf'],
  },
  mkc: {
    title: 'Megakuul Commander',
    description: 'Convenient, dashing two-column file manager for Linux',
    published: '17.07.2023',
    link: 'https://github.com/Megakuul/mkc',
    image: 'mkc.png',
    techs: ['c++', 'cmake', 'gtk'],
  },
  megakuul: {
    title: 'Megakuul.ch',
    description: 'The Website your currently looking at',
    published: '17.07.2023',
    link: 'https://github.com/Megakuul/Megakuul.ch',
    image: 'megakuul.svg',
    techs: ['svelte', 'tailwind', 'daisyui', 'vercel'],
  },
  xmemo: {
    title: 'XMemo',
    description: 'An interactive platform to play memory against other players',
    published: '17.06.2023',
    image: 'xmemo.svg',
    link: 'https://github.com/Megakuul/XMemo',
    techs: ['svelte', 'mongodb', 'nodejs', 'k8s', 'traefik'],
  },
  gorbit: {
    title: 'Gorbit',
    description: 'A blazingly fast and easy to use TCP Network Loadbalancer',
    published: '28.05.2023',
    link: 'https://github.com/Megakuul/gorbit',
    image: 'gorbit.svg',
    techs: ['go'],
  },
  grademanager: {
    title: 'GradeManager',
    description: 'Modern Cross-Plattform Grade-Manager',
    published: '18.05.2023',
    link: 'https://github.com/GradeManager',
    image: 'grademanager.png',
    techs: ['dart', 'flutter', 'c#', '.net'],
  },
  linosteffen: {
    title: 'Linosteffen.ch',
    description: 'Website for Lino Steffen',
    published: '15.05.2023',
    link: 'https://github.com/Megakuul/linosteffen.ch',
    image: 'linosteffen.png',
    techs: ['svelte', 'netlify'],
  },
  gehege: {
    title: 'Gehege',
    description: 'Example Application to host on Docker',
    published: '19.03.2023',
    link: 'https://github.com/Megakuul/gehege',
    image: 'gehege.png',
    techs: ['dart', 'flutter', 'nodejs', 'mongodb', 'docker'],
  },
  chatapp: {
    title: 'Chatapp',
    description: 'Super simple Chatapp, example to host on AWS',
    published: '27.01.2023',
    link: 'https://github.com/Megakuul/chatapp',
    image: '',
    techs: ['dart', 'flutter', 'nodejs', 'aws:rds', 'terraform', 'k8s'],
  },
  statisticcalc: {
    title: 'Statistic Calculator',
    description: 'Simple statistics calculator to display some statistical relationships in bulk',
    published: '25.11.2022',
    link: 'https://github.com/Megakuul/statisticcalc_web',
    image: 'statisticcalc.png',
    techs: ['html', 'css', 'typescript'],
  },
  dinosaurapi: {
    title: 'Dinosaur API',
    description: 'Example API meant to be hosted on Googles Cloud Platform',
    published: '03.12.2022',
    link: 'https://github.com/Megakuul/dinosaur-api-example',
    image: '',
    techs: ['dart', 'flutter', 'nodejs', 'prisma', 'gcp:cloud-sql', 'gcp:cloud-run'],
  },
  passwordgenerator: {
    title: 'Password Generator',
    description: 'The only Password Generator that actually looks good',
    published: '05.09.2022',
    link: 'https://github.com/Megakuul/passwordgenerator',
    image: 'generator.png',
    techs: ['dart', 'flutter'],
  },
  'wizard-game': {
    title: 'Wizard Game',
    description: 'Simple single player python game',
    published: '01.06.2022',
    link: 'https://github.com/Megakuul/wizard-game',
    image: 'wizard-game.png',
    techs: ['python'],
  },
};

export default projects;
