version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGISTRY="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - IMAGE_URI="$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REGISTRY"
  build:
    commands:
      - docker build --pull -f "$DOCKERFILE" -t "$IMAGE_URI" "$BUILD_CONTEXT"
  post_build:
    commands:
      - docker push "$IMAGE_URI"
