interface Project {
  title: string;
  description: string;
  published: string;
  services: string[];
}

export const projects: Record<string, Project> = {
  'pipe-plumber': {
    title: 'Pipe Plumber 🪠',
    description: 'Building a CI/CD pipeline to deploy this website',
    published: '08.01.2026',
    services: ['s3', 'acm', 'cloudfront', 'codebuild', 'cli', 'codepipeline'],
  },
  // renamed for pascal's sake
  'please-open-the-door': {
    title: 'Please open the door 🔒',
    description: 'How to authenticate with aws cli',
    published: '09.01.2026',
    services: ['cli', 'iam', 'sts'],
  },
  'how-about-a-magic-trick': {
    title: 'How about a magic trick 🎩',
    description: 'Some neat magictricks for latenight debugging sessions',
    published: '15.01.2026',
    services: ['cli', 'ssm', 'todo'],
  },
  'the-reason-aws-is-good': {
    title: 'The reason AWS is good 🗿',
    description: 'Why the AWS permission system is crazy good',
    published: '18.01.2026',
    services: ['iam', 'sts'],
  },
  wellarchitecter: {
    title: 'Wellarchitecter 🧱',
    description: 'AWS best practice buzzwords',
    published: '23.01.2026',
    services: ['iam', 'sts', 'vpc', 'todo'],
  },
  'elastic-kvm-wrapper': {
    title: 'Elastic KVM Wrapper ➰',
    description: 'Exploring virtual machines with elastic pricing',
    published: '25.01.2026',
    services: ['ec2', 'vpc', 'todo'],
  },
  paranoia: {
    title: 'Paranoia 🛠️',
    description: 'Parameterstore vs Secrets Manager ⚔️ FIGHT',
    published: '27.01.2026',
    services: ['ssm', 'secrets-manager'],
  },
  teamevent: {
    title: 'Teamevent 📅',
    description: 'How to burn your money event driven',
    published: '27.01.2026',
    services: ['events', 'todo'],
  },
  networking: {
    title: 'Networking 🌐',
    description: 'VPC is not that hard',
    published: '30.01.2026',
    services: ['vpc'],
  },
  'it-aws-dns': {
    title: 'It aws DNS 🚨',
    description: "Who would've guessed?",
    published: '31.01.2026',
    services: ['route53', 'todo'],
  },
  'transitive-gateway': {
    title: 'Transitive Gateway 💫',
    description: 'Route everything everywhere',
    published: '02.02.2026',
    services: ['vpc'],
  },
  'client-vpn': {
    title: 'Client VPN 💸',
    description: 'Make OpenVPN Expensive Again',
    published: '07.02.2026',
    services: ['vpc'],
  },
  'cloud-trailer': {
    title: 'Cloud Trailer 🚛',
    description: 'Wait, what did I just do?',
    published: '16.02.2026',
    services: ['cloudtrail', 'todo'],
  },
  'edgy-functions': {
    title: 'Edgy Functions 🎱',
    description: 'Unleash the power of servers that are less',
    published: '18.02.2026',
    services: ['lambda', 'todo'],
  },
  'the-big-s': {
    title: 'The Big 💲',
    description: 'Store your cat memes directly to a money printing machine',
    published: '25.02.2026',
    services: ['s3', 'todo'],
  },
  'api-gate': {
    title: 'api-gate 🍝',
    description: 'A service created with the dark power of spaghetti code',
    published: '26.02.2026',
    services: ['api-gateway'],
  },
  'red-feature-flag': {
    title: 'Red Feature Flag 🚩',
    description: 'Completely overcomplicate your deployment strategy with ease',
    published: '04.03.2026',
    services: ['ssm', 'todo'],
  },
  'scaler-swag': {
    title: 'Scaler Swag 📈',
    description: 'Kubernetes built by Java developers',
    published: '06.03.2026',
    services: ['ec2', 'autoscaler', 'todo'],
  },
  'inmemory-rds': {
    title: 'Inmemory RDS 🧠',
    description: "Wait a minute, isn't that just Valkey?",
    published: '18.03.2026',
    services: ['elasticache', 'todo'],
  },
  'simple-tube': {
    title: 'Simple Tube Service 🧪',
    description: 'Why is message broker just one letter away from "message broken"?',
    published: '23.03.2026',
    services: ['sqs', 'sns', 'todo'],
  },
  'elite-kubernetes-shenanigans': {
    title: 'Elite Kubernetes Shenanigans 🦅',
    description: 'Not even AWS dared to call it "Simple Kubernetes Service"',
    published: '25.04.2026',
    services: ['eks', 'todo'],
  },
  incognito: {
    title: 'Incognito 🥸',
    description: "Guys we haven't read the OIDC spec either",
    published: '30.04.2026',
    services: ['cognito', 'todo'],
  },
  lambda: {
    title: 'Lambda Cheatsheet',
    description: 'The Big Beautiful Lambda Cheatsheet',
    published: '31.07.2026',
    services: ['lambda', 'api-gateway', 'sqs', 'sns', 'events'],
  },
  kubernetes: {
    title: 'Kubernetes Cheatsheet',
    description: 'The Big Beautiful EKS Cheatsheet',
    published: '01.09.2026',
    services: ['eks', 'iam'],
  },
  checklist: {
    title: 'Well-Architected Checklist',
    description: 'Every technical best practice to verify before the clock runs out',
    published: '01.09.2026',
    services: [
      'iam',
      'vpc',
      'ec2',
      'elb',
      's3',
      'cloudfront',
      'route53',
      'rds',
      'dynamodb',
      'elasticache',
      'lambda',
      'api-gateway',
      'sqs',
      'sns',
      'events',
      'eks',
      'ssm',
      'secrets-manager',
      'acm',
      'waf',
      'guardduty',
      'cloudtrail',
      'cloudwatch',
      'backup',
      'cognito',
    ],
  },
  watchout: {
    title: 'Watch Out 🙈',
    description: 'Who is grafana? should I know this guy?',
    published: '10.08.2026',
    services: ['cloudwatch'],
  },
  'iam-conditions': {
    title: 'IAM Cheatsheet',
    description: 'The Big Beautiful IAM Condition Cheatsheet',
    published: '30.08.2026',
    services: ['iam', 'sts', 'cognito'],
  },
  gadgets: {
    title: 'Gadgets',
    description: 'Lambda utilities and dashboards',
    published: '03.09.2026',
    services: [
      'lambda',
      'cloudwatch',
      'api-gateway',
      'sqs',
      'kinesis',
      'dynamodb',
      'rds',
      'redshift',
      'elasticache',
      'ecr',
      'codebuild',
    ],
  },
  codepipeline: {
    title: 'CodePipeline',
    description: 'Source, build, test, approval, and deployment examples',
    published: '05.09.2026',
    services: [
      'codepipeline',
      'codebuild',
      'codedeploy',
      'lambda',
      'ecr',
      'ecs',
      'ec2',
      's3',
      'cloudformation',
    ],
  },
};

export default projects;
